
export let schemaEnum={
    SCHEMA_TYPE:['string', 'number', 'array', 'object', 'boolean', 'integer'],

    MOCK_SOURCE:[
        { value: '@string' },
        { value: '@natural' },
        { value: '@float' },
        { value: '@character' },
        { value: '@boolean' },
        { value: '@url' },
        { value: '@domain' },
        { value: '@ip' },
        { value: '@id' },
        { value: '@guid' },
        { value: '@now' },
        { value: '@timestamp'},
        { value: '@date' },
        { value: '@time' },
        { value: '@datetime' },
        { value: '@image' },
        { value: "@imageData" },
        { value: '@color' },
        { value: '@hex' },
        { value: '@rgba' },
        { value: '@rgb' },
        { value: '@hsl' },
        { value: '@integer' },
        { value: '@email' },
        { value: '@paragraph' },
        { value: '@sentence' },
        { value: '@word' },
        { value: '@cparagraph' },
        { value: '@ctitle' },
        { value: '@title' },
        { value: '@name' },
        { value: '@cname' },
        { value: '@cfirst' },
        { value: '@clast' },
        { value: '@first' },
        { value: '@last' },
        { value: '@csentence' },
        { value: '@cword' },
        { value: '@region' },
        { value: '@province' },
        { value: '@city' },
        { value: '@county' },
        { value: '@upper' },
        { value: '@lower' },
        { value: '@pick' },
        { value: '@shuffle' },
        { value: '@protocol' }
    ]

}